pushd .
cd /cms_scratch/bhoh/toys/impact_mH75
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_mH80
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_mH85
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_mH90
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_mH100
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_mH110
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_mH120
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_mH130
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_mH140
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_mH150
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_mH160
condor_submit condor_combine_task.sub
#sleep 5m
#cd /cms_scratch/bhoh/toys/impact_mH150_noDL
#condor_submit condor_combine_task.sub
popd
