pushd .
cd /cms_scratch/bhoh/toys/impact_morphed_mH75
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_morphed_mH80
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_morphed_mH85
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_morphed_mH90
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_morphed_mH100
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_morphed_mH110
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_morphed_mH120
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_morphed_mH130
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_morphed_mH140
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_morphed_mH150
condor_submit condor_combine_task.sub
sleep 5m
cd /cms_scratch/bhoh/toys/impact_morphed_mH160
condor_submit condor_combine_task.sub
popd
