#samples[<year>][<kind>]

#samples = {
#  '2016' : {
#        ('<prod>','DATA') :[
#            ],
#        ('<prod>','MC') :[
#            ],
#        ('<prod>','MC_ttsyst') :[
#            ],
#        ('<prod>','MC_signal') :[
#            ],
#      },
#  '2017' : {
#        ('<prod>','DATA') :[
#            ],
#        ('<prod>','MC') :[
#            ],
#        ('<prod>','MC_ttsyst') :[
#            ],
#        ('<prod>','MC_signal') :[
#            ],
#      },
#  '2018' : {
#        ('<prod>','DATA') :[
#            ],
#        ('<prod>','MC') :[
#            ],
#        ('<prod>','MC_ttsyst') :[
#            ],
#        ('<prod>','MC_signal') :[
#            ],
#      },
#
#}

#sample defs. per year and production

samples = {
  '2016' : {
        ('Run2016_102X_nAODv5_Full2016v6','DATA') :[
                'SingleElectron_Run2016B-Nano1June2019_ver2-v1',
                'SingleElectron_Run2016C-Nano1June2019-v1',
                'SingleElectron_Run2016D-Nano1June2019-v1',
                'SingleElectron_Run2016E-Nano1June2019-v1',
                'SingleElectron_Run2016F-Nano1June2019-v1',
                'SingleElectron_Run2016G-Nano1June2019-v1',
                'SingleElectron_Run2016H-Nano1June2019-v1',
                'SingleMuon_Run2016B-Nano1June2019_ver2-v1',
                'SingleMuon_Run2016C-Nano1June2019-v1',
                'SingleMuon_Run2016D-Nano1June2019-v1',
                'SingleMuon_Run2016E-Nano1June2019-v1',
                'SingleMuon_Run2016F-Nano1June2019-v1',
                'SingleMuon_Run2016G-Nano1June2019-v1',
                'SingleMuon_Run2016H-Nano1June2019-v1',
            ],
        ('Summer16_102X_nAODv5_Full2016v6','MC') :[
                'DYJetsToLL_M-10to50-LO',
                'DYJetsToLL_M-50-LO_ext1',
                'DYJetsToLL_M-50-LO_ext2',
                'DYJetsToLL_M-10to50',
                'DYJetsToLL_M-10to50_ext1',
                'DYJetsToLL_M-50_ext2',
                'DYJetsToLL_M-50-UEup',
                'DYJetsToLL_M-50-UEdo',
                'DYJetsToLL_M-50-PSup',
                'DYJetsToLL_M-50-PSdo',
                'DYJetsToLL_M-5to50_HT-70to100',
                'DYJetsToLL_M-5to50_HT-100to200',
                'DYJetsToLL_M-5to50_HT-100to200_ext1',
                'DYJetsToLL_M-5to50_HT-200to400',
                'DYJetsToLL_M-5to50_HT-200to400_ext1',
                'DYJetsToLL_M-5to50_HT-400to600',
                'DYJetsToLL_M-5to50_HT-400to600_ext1',
                'DYJetsToLL_M-5to50_HT-600toinf',
                'DYJetsToLL_M-50_HT-70to100',
                'DYJetsToLL_M-50_HT-100to200',
                'DYJetsToLL_M-50_HT-100to200_ext1',
                'DYJetsToLL_M-50_HT-200to400',
                'DYJetsToLL_M-50_HT-200to400_ext1',
                'DYJetsToLL_M-50_HT-400to600',
                'DYJetsToLL_M-50_HT-400to600_ext1',
                'DYJetsToLL_M-50_HT-600to800',
                'DYJetsToLL_M-50_HT-800to1200',
                'DYJetsToLL_M-50_HT-1200to2500',
                'DYJetsToLL_M-50_HT-2500toinf',
                'GluGluHToWWToLNuQQ_M115',
                'GluGluHToWWToLNuQQ_M120',
                'GluGluHToWWToLNuQQ_M124',
                'GluGluHToWWToLNuQQ_M125',
                'GluGluHToWWToLNuQQ_M126',
                'GluGluHToWWToLNuQQ_M130',
                'GluGluHToWWToLNuQQ_M135',
                'GluGluHToWWToLNuQQ_M140',
                'GluGluHToWWToLNuQQ_M145',
                'GluGluHToWWToLNuQQ_M150',
                'GluGluHToWWToLNuQQ_M155',
                'GluGluHToWWToLNuQQ_M160',
                'GluGluHToWWToLNuQQ_M165',
                'GluGluHToWWToLNuQQ_M170',
                'GluGluHToWWToLNuQQ_M175',
                'GluGluHToWWToLNuQQ_M180',
                'GluGluHToWWToLNuQQ_M190',
                'GluGluHToWWToLNuQQ_M200',
                'GluGluHToWWToLNuQQ_M210',
                'GluGluHToWWToLNuQQ_M230',
                'GluGluHToWWToLNuQQ_M250',
                'GluGluHToWWToLNuQQ_M270',
                'GluGluHToWWToLNuQQ_M300',
                'GluGluHToWWToLNuQQ_M350',
                'GluGluHToWWToLNuQQ_M400',
                'GluGluHToWWToLNuQQ_M450',
                'GluGluHToWWToLNuQQ_M500',
                'GluGluHToWWToLNuQQ_M550',
                'GluGluHToWWToLNuQQ_M600',
                'GluGluHToWWToLNuQQ_M650',
                'GluGluHToWWToLNuQQ_M700',
                'GluGluHToWWToLNuQQ_M750',
                'GluGluHToWWToLNuQQ_M800',
                'GluGluHToWWToLNuQQ_M900',
                'GluGluHToWWToLNuQQ_M1000',
                'GluGluHToWWToLNuQQ_M1500',
                'GluGluHToWWToLNuQQ_M2000',
                'GluGluHToWWToLNuQQ_M2500',
                'GluGluHToWWToLNuQQ_M3000',
                'GluGluHToWWToLNuQQ_M4000',
                'GluGluHToWWToLNuQQ_M5000',
                'QCD_Pt-15to20_MuEnrichedPt5',
                'QCD_Pt-20toInf_MuEnrichedPt15',
                'QCD_Pt-20to30_EMEnriched',
                'QCD_Pt-30to50_EMEnriched',
                'QCD_Pt-50to80_EMEnriched',
                'QCD_Pt-80to120_EMEnriched',
                'QCD_Pt-120to170_EMEnriched',
                'QCD_Pt-170to300_EMEnriched',
                'QCD_Pt-300toInf_EMEnriched',
                'QCD_Pt_15to20_bcToE',
                'QCD_Pt_20to30_bcToE',
                'QCD_Pt_30to80_bcToE',
                'QCD_Pt_80to170_bcToE',
                'QCD_Pt_170to250_bcToE',
                'QCD_Pt_250toInf_bcToE',
                'TTToSemiLeptonic',
                'TTTo2L2Nu',
                'ST_t-channel_top',
                'ST_t-channel_antitop',
                'ST_tW_antitop',
                'ST_tW_top',
                'ST_s-channel',
                'TTWJetsToLNu',
                'TTWJetsToQQ',
                'TTZjets',
                'VBFHToWWToLNuQQ_M115',
                'VBFHToWWToLNuQQ_M120',
                'VBFHToWWToLNuQQ_M124',
                'VBFHToWWToLNuQQ_M125',
                'VBFHToWWToLNuQQ_M126',
                'VBFHToWWToLNuQQ_M130',
                'VBFHToWWToLNuQQ_M135',
                'VBFHToWWToLNuQQ_M140',
                'VBFHToWWToLNuQQ_M145',
                'VBFHToWWToLNuQQ_M150',
                'VBFHToWWToLNuQQ_M160',
                'VBFHToWWToLNuQQ_M165',
                'VBFHToWWToLNuQQ_M170',
                'VBFHToWWToLNuQQ_M175',
                'VBFHToWWToLNuQQ_M180',
                'VBFHToWWToLNuQQ_M190',
                'VBFHToWWToLNuQQ_M200',
                'VBFHToWWToLNuQQ_M210',
                'VBFHToWWToLNuQQ_M230',
                'VBFHToWWToLNuQQ_M250',
                'VBFHToWWToLNuQQ_M270',
                'VBFHToWWToLNuQQ_M300',
                'VBFHToWWToLNuQQ_M350',
                'VBFHToWWToLNuQQ_M400',
                'VBFHToWWToLNuQQ_M450',
                'VBFHToWWToLNuQQ_M500',
                'VBFHToWWToLNuQQ_M550',
                'VBFHToWWToLNuQQ_M600',
                'VBFHToWWToLNuQQ_M650',
                'VBFHToWWToLNuQQ_M700',
                'VBFHToWWToLNuQQ_M750',
                'VBFHToWWToLNuQQ_M800',
                'VBFHToWWToLNuQQ_M900',
                'VBFHToWWToLNuQQ_M1000',
                'VBFHToWWToLNuQQ_M1500',
                'VBFHToWWToLNuQQ_M2000',
                'VBFHToWWToLNuQQ_M2500',
                'VBFHToWWToLNuQQ_M3000',
                'VBFHToWWToLNuQQ_M4000',
                'VBFHToWWToLNuQQ_M5000',
                'WJetsToLNu_HT70_100',
                'WJetsToLNu_HT100_200',
                'WJetsToLNu_HT100_200_ext1',
                'WJetsToLNu_HT100_200_ext2',
                'WJetsToLNu_HT200_400',
                'WJetsToLNu_HT200_400_ext1',
                'WJetsToLNu_HT200_400_ext2',
                'WJetsToLNu_HT400_600',
                'WJetsToLNu_HT400_600_ext1',
                'WJetsToLNu_HT600_800',
                'WJetsToLNu_HT600_800_ext1',
                'WJetsToLNu_HT800_1200',
                'WJetsToLNu_HT800_1200_ext1',
                'WJetsToLNu_HT1200_2500',
                'WJetsToLNu_HT1200_2500_ext1',
                'WJetsToLNu_HT2500_inf',
                'WJetsToLNu_HT2500_inf_ext1',
                'WJetsToLNu',
                'WJetsToLNu_ext2',
                'WWToLNuQQ',
                'WWToLNuQQ_AMCNLOFXFX',
                'WZ',
                'WZ_ext',
                'ZZ',
                'ZZ_ext1',
                'WWW',
                'WWZ',
                'WZZ',
                'ZZZ',
                'WWG',
                'WpWmJJ_EWK_QCD_noHiggs',
            ],
        ('Summer16_102X_nAODv5_Full2016v6','MC_ttsyst') :[
                'TT_TuneCUETP8M2T4Up',
                'TT_TuneCUETP8M2T4Down',
                'TT_hdampUp',
                'TT_hdampDown',
                'TT_mtopUp',
                'TT_mtopDown',
            ],
        ('Summer16_102X_nAODv5_Full2016v6','MC_signal') :[
                'CHToCB_M060',
                'CHToCB_M070',
                'CHToCB_M075',
                'CHToCB_M080',
                'CHToCB_M085',
                'CHToCB_M090',
                'CHToCB_M100',
                'CHToCB_M110',
                'CHToCB_M120',
                'CHToCB_M130',
                'CHToCB_M140',
                'CHToCB_M150',
            ],
      },
  '2017' : {
        ('Run2017_102X_nAODv5_Full2017v6','DATA') :[
                'SingleElectron_Run2017B-Nano1June2019-v1',
                'SingleElectron_Run2017C-Nano1June2019-v1',
                'SingleElectron_Run2017D-Nano1June2019-v1',
                'SingleElectron_Run2017E-Nano1June2019-v1',
                'SingleElectron_Run2017F-Nano1June2019-v1',
                'SingleMuon_Run2017B-Nano1June2019-v1',
                'SingleMuon_Run2017C-Nano1June2019-v1',
                'SingleMuon_Run2017D-Nano1June2019-v1',
                'SingleMuon_Run2017E-Nano1June2019-v1',
                'SingleMuon_Run2017F-Nano1June2019-v1',
            ],
        ('Fall2017_102X_nAODv5_Full2017v6','MC') :[
                'DYJetsToLL_M-5to50-LO',
                'DYJetsToLL_M-10to50-LO',
                'DYJetsToLL_M-10to50-LO_ext1',
                'DYJetsToLL_M-50-LO',
                'DYJetsToLL_M-50-LO_ext1',
                'DYJetsToLL_M-50',
                'DYJetsToLL_M-4to50_HT-100to200',
                'DYJetsToLL_M-4to50_HT-100to200_ext1',
                'DYJetsToLL_M-4to50_HT-200to400',
                'DYJetsToLL_M-4to50_HT-200to400_ext1',
                'DYJetsToLL_M-4to50_HT-400to600',
                'DYJetsToLL_M-4to50_HT-400to600_ext1',
                'DYJetsToLL_M-4to50_HT-600toInf',
                'DYJetsToLL_M-4to50_HT-600toInf_ext1',
                'DYJetsToLL_M-50_HT-100to200',
                'DYJetsToLL_M-50_HT-200to400',
                'DYJetsToLL_M-50_HT-200to400_ext1',
                'DYJetsToLL_M-50_HT-400to600_ext1',
                'DYJetsToLL_M-50_HT-600to800',
                'DYJetsToLL_M-50_HT-800to1200',
                'DYJetsToLL_M-50_HT-1200to2500',
                'DYJetsToLL_M-50_HT-2500toInf',
                'GluGluHToWWToLNuQQ_M115',
                'GluGluHToWWToLNuQQ_M120',
                'GluGluHToWWToLNuQQ_M125',
                'GluGluHToWWToLNuQQ_M126',
                'GluGluHToWWToLNuQQ_M130',
                'GluGluHToWWToLNuQQ_M135',
                'GluGluHToWWToLNuQQ_M140',
                'GluGluHToWWToLNuQQ_M145',
                'GluGluHToWWToLNuQQ_M150',
                'GluGluHToWWToLNuQQ_M155',
                'GluGluHToWWToLNuQQ_M160',
                'GluGluHToWWToLNuQQ_M165',
                'GluGluHToWWToLNuQQ_M170',
                'GluGluHToWWToLNuQQ_M175',
                'GluGluHToWWToLNuQQ_M180',
                'GluGluHToWWToLNuQQ_M200',
                'GluGluHToWWToLNuQQ_M210',
                'GluGluHToWWToLNuQQ_M230',
                'GluGluHToWWToLNuQQ_M250',
                'GluGluHToWWToLNuQQ_M270',
                'GluGluHToWWToLNuQQ_M300',
                'GluGluHToWWToLNuQQ_M350',
                'GluGluHToWWToLNuQQ_M400',
                'GluGluHToWWToLNuQQ_M450',
                'GluGluHToWWToLNuQQ_M500',
                'GluGluHToWWToLNuQQ_M550',
                'GluGluHToWWToLNuQQ_M600',
                'GluGluHToWWToLNuQQ_M650',
                'GluGluHToWWToLNuQQ_M700',
                'GluGluHToWWToLNuQQ_M750',
                'GluGluHToWWToLNuQQ_M800',
                'GluGluHToWWToLNuQQ_M900',
                'GluGluHToWWToLNuQQ_M1000',
                'GluGluHToWWToLNuQQ_M1500',
                'GluGluHToWWToLNuQQ_M2000',
                'GluGluHToWWToLNuQQ_M2500',
                'GluGluHToWWToLNuQQ_M3000',
                'GluGluHToWWToLNuQQ_M4000',
                'GluGluHToWWToLNuQQ_M5000',
                'QCD_Pt-15to20_MuEnrichedPt5',
                'QCD_Pt-20to30_MuEnrichedPt5',
                'QCD_Pt-30to50_MuEnrichedPt5',
                'QCD_Pt-50to80_MuEnrichedPt5',
                'QCD_Pt-80to120_MuEnrichedPt5',
                'QCD_Pt-120to170_MuEnrichedPt5',
                'QCD_Pt-170to300_MuEnrichedPt5',
                'QCD_Pt-300to470_MuEnrichedPt5',
                'QCD_Pt-470to600_MuEnrichedPt5',
                'QCD_Pt-600to800_MuEnrichedPt5',
                'QCD_Pt-800to1000_MuEnrichedPt5',
                'QCD_Pt-1000toInf_MuEnrichedPt5',
                'QCD_Pt-15to20_EMEnriched',
                'QCD_Pt-20to30_EMEnriched',
                'QCD_Pt-30to50_EMEnriched',
                'QCD_Pt-50to80_EMEnriched',
                'QCD_Pt-80to120_EMEnriched',
                'QCD_Pt-120to170_EMEnriched',
                'QCD_Pt-170to300_EMEnriched',
                'QCD_Pt-300toInf_EMEnriched',
                'TTToSemiLeptonic',
                'TTTo2L2Nu_PSWeights',
                'ST_t-channel_top',
                'ST_t-channel_antitop',
                'ST_tW_antitop',
                'ST_tW_top',
                'ST_s-channel',
                'TTWjets',
                'TTWjets_ext1',
                'TTZjets',
                'TTZjets_ext1',
                'VBFHToWWToLNuQQ_M115',
                'VBFHToWWToLNuQQ_M120',
                'VBFHToWWToLNuQQ_M124',
                'VBFHToWWToLNuQQ_M125',
                'VBFHToWWToLNuQQ_M126',
                'VBFHToWWToLNuQQ_M130',
                'VBFHToWWToLNuQQ_M140',
                'VBFHToWWToLNuQQ_M145',
                'VBFHToWWToLNuQQ_M150',
                'VBFHToWWToLNuQQ_M155',
                'VBFHToWWToLNuQQ_M160',
                'VBFHToWWToLNuQQ_M165',
                'VBFHToWWToLNuQQ_M170',
                'VBFHToWWToLNuQQ_M180',
                'VBFHToWWToLNuQQ_M190',
                'VBFHToWWToLNuQQ_M200',
                'VBFHToWWToLNuQQ_M210',
                'VBFHToWWToLNuQQ_M230',
                'VBFHToWWToLNuQQ_M250',
                'VBFHToWWToLNuQQ_M270',
                'VBFHToWWToLNuQQ_M300',
                'VBFHToWWToLNuQQ_M350',
                'VBFHToWWToLNuQQ_M400',
                'VBFHToWWToLNuQQ_M450',
                'VBFHToWWToLNuQQ_M500',
                'VBFHToWWToLNuQQ_M550',
                'VBFHToWWToLNuQQ_M600',
                'VBFHToWWToLNuQQ_M650',
                'VBFHToWWToLNuQQ_M700',
                'VBFHToWWToLNuQQ_M750',
                'VBFHToWWToLNuQQ_M800',
                'VBFHToWWToLNuQQ_M900',
                'VBFHToWWToLNuQQ_M1000',
                'VBFHToWWToLNuQQ_M1500',
                'VBFHToWWToLNuQQ_M2000',
                'VBFHToWWToLNuQQ_M2500',
                'VBFHToWWToLNuQQ_M3000',
                'VBFHToWWToLNuQQ_M4000',
                'VBFHToWWToLNuQQ_M5000',
                'WJetsToLNu-0J',
                'WJetsToLNu-1J',
                'WJetsToLNu-2J',
                'WW-LO',
                'WWToLNuQQ',
                'QCD_Pt_20to30_bcToE',
                'QCD_Pt_20to30_bcToE_newpmx',
                'QCD_Pt_30to80_bcToE',
                'QCD_Pt_80to170_bcToE',
                'QCD_Pt_170to250_bcToE',
                'QCD_Pt_250toInf_bcToE',
                'QCD_Pt_170to300',
                'QCD_Pt_170to300_ext1',
                'WZ',
                'ZZ',
                'ZZZ',
                'WWW',
                'WZZ',
                'WWZ',
                'WpWmJJ_EWK_QCD_noHiggs',
            ],
        ('Fall2017_102X_nAODv5_Full2017v6','MC_ttsyst') :[
                'TTToSemiLeptonic_TuneCP5Up',
                'TTToSemiLeptonic_TuneCP5Down',
                'TTTo2L2Nu_TuneCP5Up',
                'TTTo2L2Nu_TuneCP5Down',
                'TTToSemiLeptonic_hdampUp',
                'TTToSemiLeptonic_hdampDown',
                'TTTo2L2Nu_hdampUp',
                'TTTo2L2Nu_hdampDown',
                'TTToSemiLeptonic_mtopUp',
                'TTToSemiLeptonic_mtopDown',
                'TTTo2L2Nu_mtopUp', 
                'TTTo2L2Nu_mtopDown',
            ],
        ('Fall2017_102X_nAODv5_Full2017v6','MC_signal') :[
                'CHToCB_M050',
                'CHToCB_M060',
                'CHToCB_M070',
                'CHToCB_M075',
                'CHToCB_M080',
                'CHToCB_M085',
                'CHToCB_M090',
                'CHToCB_M100',
                'CHToCB_M110',
                'CHToCB_M120',
                'CHToCB_M130',
                'CHToCB_M140',
                'CHToCB_M150',
            ],
      },
  '2018' : {
        ('Run2018_102X_nAODv6_Full2018v6','DATA') :[
                      'EGamma_Run2018A-Nano25Oct2019-v1',
                      'EGamma_Run2018B-Nano25Oct2019-v1',
                      'EGamma_Run2018C-Nano25Oct2019-v1',
                      'EGamma_Run2018D-Nano25Oct2019_ver2-v1',
                      'SingleMuon_Run2018A-Nano25Oct2019-v1',
                      'SingleMuon_Run2018B-Nano25Oct2019-v1',
                      'SingleMuon_Run2018C-Nano25Oct2019-v1',
                      'SingleMuon_Run2018D-Nano25Oct2019_ver2-v1',
            ],
        ('Autumn18_102X_nAODv6_Full2018v6','MC') :[
                     'DYJetsToLL_M-4to50_HT-200to400',
                     'DYJetsToLL_M-4to50_HT-400to600',
                     'DYJetsToLL_M-4to50_HT-600toInf',
                     'DYJetsToLL_M-10to50-LO_ext1',
                     'DYJetsToLL_M-10to50-LO',
                     'DYJetsToLL_M-50-LO',
                     'DYJetsToLL_M-50_HT-70to100',
                     'DYJetsToLL_M-50_HT-100to200',
                     'DYJetsToLL_M-50_HT-200to400',
                     'DYJetsToLL_M-50_HT-400to600',
                     'DYJetsToLL_M-50_HT-600to800',
                     'DYJetsToLL_M-50_HT-800to1200',
                     'DYJetsToLL_M-50_HT-1200to2500',
                     'DYJetsToLL_M-50_HT-2500toInf',
                     'GluGluHToWWToLNuQQ_M115',
                     'GluGluHToWWToLNuQQ_M120',
                     'GluGluHToWWToLNuQQ_M124',
                     'GluGluHToWWToLNuQQ_M125',
                     'GluGluHToWWToLNuQQ_M126',
                     'GluGluHToWWToLNuQQ_M130',
                     'GluGluHToWWToLNuQQ_M135',
                     'GluGluHToWWToLNuQQ_M140',
                     'GluGluHToWWToLNuQQ_M145',
                     'GluGluHToWWToLNuQQ_M150',
                     'GluGluHToWWToLNuQQ_M155',
                     'GluGluHToWWToLNuQQ_M160',
                     'GluGluHToWWToLNuQQ_M165',
                     'GluGluHToWWToLNuQQ_M170',
                     'GluGluHToWWToLNuQQ_M175',
                     'GluGluHToWWToLNuQQ_M180',
                     'GluGluHToWWToLNuQQ_M190',
                     'GluGluHToWWToLNuQQ_M200',
                     'GluGluHToWWToLNuQQ_M210',
                     'GluGluHToWWToLNuQQ_M230',
                     'GluGluHToWWToLNuQQ_M250',
                     'GluGluHToWWToLNuQQ_M270',
                     'GluGluHToWWToLNuQQ_M300',
                     'GluGluHToWWToLNuQQ_M350',
                     'GluGluHToWWToLNuQQ_M400',
                     'GluGluHToWWToLNuQQ_M450',
                     'GluGluHToWWToLNuQQ_M500',
                     'GluGluHToWWToLNuQQ_M550',
                     'GluGluHToWWToLNuQQ_M600',
                     'GluGluHToWWToLNuQQ_M650',
                     'GluGluHToWWToLNuQQ_M700',
                     'GluGluHToWWToLNuQQ_M750',
                     'GluGluHToWWToLNuQQ_M800',
                     'GluGluHToWWToLNuQQ_M900',
                     'GluGluHToWWToLNuQQ_M1000',
                     'GluGluHToWWToLNuQQ_M1500',
                     'GluGluHToWWToLNuQQ_M2000',
                     'GluGluHToWWToLNuQQ_M2500',
                     'GluGluHToWWToLNuQQ_M3000',
                     'GluGluHToWWToLNuQQ_M4000',
                     'GluGluHToWWToLNuQQ_M5000',
                     'QCD_Pt-15to20_MuEnrichedPt5',
                     'QCD_Pt-20to30_MuEnrichedPt5',
                     'QCD_Pt-30to50_MuEnrichedPt5',
                     'QCD_Pt-50to80_MuEnrichedPt5',
                     'QCD_Pt-80to120_MuEnrichedPt5',
                     'QCD_Pt-80to120_MuEnrichedPt5_ext1',
                     'QCD_Pt-120to170_MuEnrichedPt5',
                     'QCD_Pt-120to170_MuEnrichedPt5_ext1',
                     'QCD_Pt-170to300_MuEnrichedPt5',
                     'QCD_Pt-300to470_MuEnrichedPt5',
                     'QCD_Pt-300to470_MuEnrichedPt5_ext3',
                     'QCD_Pt-470to600_MuEnrichedPt5',
                     'QCD_Pt-470to600_MuEnrichedPt5_ext1',
                     'QCD_Pt-600to800_MuEnrichedPt5',
                     'QCD_Pt-800to1000_MuEnrichedPt5',
                     'QCD_Pt-1000toInf_MuEnrichedPt5',
                     'QCD_Pt-15to20_EMEnriched',
                     'QCD_Pt-20to30_EMEnriched',
                     'QCD_Pt-30to50_EMEnriched',
                     'QCD_Pt-50to80_EMEnriched',
                     'QCD_Pt-80to120_EMEnriched',
                     'QCD_Pt-120to170_EMEnriched',
                     'QCD_Pt-170to300_EMEnriched',
                     'QCD_Pt-300toInf_EMEnriched',
                     'ST_t-channel_top',
                     'ST_t-channel_antitop',
                     'ST_tW_top_ext1',
                     'ST_tW_antitop_ext1',
                     'ST_s-channel_ext1',
                     'TTToSemiLeptonic',
                     'TTTo2L2Nu',
                     'TTToSemiLeptonic_ext3',
                     'TTZjets',
                     'TTWjets',
                     'VBFHToWWToLNuQQ_M115',
                     'VBFHToWWToLNuQQ_M120',
                     'VBFHToWWToLNuQQ_M124',
                     'VBFHToWWToLNuQQ_M125',
                     'VBFHToWWToLNuQQ_M126',
                     'VBFHToWWToLNuQQ_M130',
                     'VBFHToWWToLNuQQ_M135',
                     'VBFHToWWToLNuQQ_M140',
                     'VBFHToWWToLNuQQ_M145',
                     'VBFHToWWToLNuQQ_M150',
                     'VBFHToWWToLNuQQ_M155',
                     'VBFHToWWToLNuQQ_M160',
                     'VBFHToWWToLNuQQ_M165',
                     'VBFHToWWToLNuQQ_M170',
                     'VBFHToWWToLNuQQ_M175',
                     'VBFHToWWToLNuQQ_M180',
                     'VBFHToWWToLNuQQ_M190',
                     'VBFHToWWToLNuQQ_M200',
                     'VBFHToWWToLNuQQ_M210',
                     'VBFHToWWToLNuQQ_M230',
                     'VBFHToWWToLNuQQ_M250',
                     'VBFHToWWToLNuQQ_M270',
                     'VBFHToWWToLNuQQ_M300',
                     'VBFHToWWToLNuQQ_M350',
                     'VBFHToWWToLNuQQ_M400',
                     'VBFHToWWToLNuQQ_M450',
                     'VBFHToWWToLNuQQ_M500',
                     'VBFHToWWToLNuQQ_M550',
                     'VBFHToWWToLNuQQ_M600',
                     'VBFHToWWToLNuQQ_M650',
                     'VBFHToWWToLNuQQ_M700',
                     'VBFHToWWToLNuQQ_M750',
                     'VBFHToWWToLNuQQ_M800',
                     'VBFHToWWToLNuQQ_M900',
                     'VBFHToWWToLNuQQ_M1000',
                     'VBFHToWWToLNuQQ_M1500',
                     'VBFHToWWToLNuQQ_M2000',
                     'VBFHToWWToLNuQQ_M2500',
                     'VBFHToWWToLNuQQ_M3000',
                     'VBFHToWWToLNuQQ_M4000',
                     'VBFHToWWToLNuQQ_M5000',
                     'WJetsToLNu-0J',
                     'WJetsToLNu-1J',
                     'WJetsToLNu-2J',
                     'WW-LO',
                     'WWToLNuQQ',
                     'WWToLNuQQ_AMCATNLO',
                     'WZ',
                     'ZZ',
                     'WWW',
                     'WWZ',
                     'WZZ',
                     'ZZZ',
                     'QCD_Pt_20to30_bcToE',
                     'QCD_Pt_30to80_bcToE',
                     'QCD_Pt_80to170_bcToE',
                     'QCD_Pt_170to250_bcToE',
                     'QCD_Pt_250toInf_bcToE',
                     'WpWmJJ_EWK_QCD_noHiggs',

            ],
        ('Autumn18_102X_nAODv6_Full2018v6','MC_ttsyst') :[
                'TTToSemiLeptonic_TuneCP5Up',
                'TTToSemiLeptonic_TuneCP5Down',
                'TTTo2L2Nu_TuneCP5Up',
                'TTTo2L2Nu_TuneCP5Down',
                'TTToSemiLeptonic_hdampUp',
                'TTToSemiLeptonic_hdampDown',
                'TTTo2L2Nu_hdampUp',
                'TTTo2L2Nu_hdampDown',
                'TTToSemiLeptonic_mtopUp',
                'TTToSemiLeptonic_mtopDown',
                'TTTo2L2Nu_mtopUp', 
                'TTTo2L2Nu_mtopDown',
            ],
        ('Autumn18_102X_nAODv6_Full2018v6','MC_signal') :[
                     'CHToCB_M075',
                     'CHToCB_M080',
                     'CHToCB_M085',
                     'CHToCB_M090',
                     'CHToCB_M100',
                     'CHToCB_M110',
                     'CHToCB_M120',
                     'CHToCB_M130',
                     'CHToCB_M140',
                     'CHToCB_M150',
            ],
      },

}

# post-processing configuration per year and production
# will modify this by skim-steps! ('<prod>',<step>,<data_or_MC_or_Other>)
# ('<prod>','ELSE',<data_or_MC_or_Other>)
modCfgs = {
  '2016' : {
        ('Run2016_102X_nAODv5_Full2016v6','DATA') :[
              '--sitescfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Sites_cfg.py',
              '--modcfg SNuAnalytics/NanoGardenerFrameworks/Steps_cfg.py',
            ],
        ('Summer16_102X_nAODv5_Full2016v6','MC') :[
              '--sitescfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Sites_cfg.py',
              '--modcfg SNuAnalytics/NanoGardenerFrameworks/Steps_cfg.py',
            ],
        ('Summer16_102X_nAODv5_Full2016v6','MC_ttsyst') :[
              '--sitescfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Sites_cfg.py',
              '--modcfg SNuAnalytics/NanoGardenerFrameworks/Steps_cfg.py',
              '--datacfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Productions_cfg.py',
            ],
        ('Summer16_102X_nAODv5_Full2016v6','MC_signal') :[
              '--sitescfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Sites_cfg.py',
              '--modcfg SNuAnalytics/NanoGardenerFrameworks/Steps_cfg.py',
              '--datacfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Productions_cfg.py',
            ],
      },
  '2017' : {
        ('Run2017_102X_nAODv5_Full2017v6','DATA') :[
              '--sitescfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Sites_cfg.py',
              '--modcfg SNuAnalytics/NanoGardenerFrameworks/Steps_cfg.py',
            ],
        ('Fall2017_102X_nAODv5_Full2017v6','MC') :[
              '--sitescfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Sites_cfg.py',
              '--modcfg SNuAnalytics/NanoGardenerFrameworks/Steps_cfg.py',
            ],
        ('Fall2017_102X_nAODv5_Full2017v6','MC_ttsyst') :[
              '--sitescfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Sites_cfg.py',
              '--modcfg SNuAnalytics/NanoGardenerFrameworks/Steps_cfg.py',
              '--datacfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Productions_cfg.py',
            ],
        ('Fall2017_102X_nAODv5_Full2017v6','MC_signal') :[
              '--sitescfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Sites_cfg.py',
              '--modcfg SNuAnalytics/NanoGardenerFrameworks/Steps_cfg.py',
              '--datacfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Productions_cfg.py',
            ],
      },
  '2018' : {
        ('Run2018_102X_nAODv6_Full2018v6','DATA') :[
              '--sitescfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Sites_cfg.py',
              '--modcfg SNuAnalytics/NanoGardenerFrameworks/Steps_cfg.py',
            ],
        ('Autumn18_102X_nAODv6_Full2018v6','MC') :[
              '--sitescfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Sites_cfg.py',
              '--modcfg SNuAnalytics/NanoGardenerFrameworks/Steps_cfg.py',
            ],
        ('Autumn18_102X_nAODv6_Full2018v6','MC_ttsyst') :[
              '--sitescfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Sites_cfg.py',
              '--modcfg SNuAnalytics/NanoGardenerFrameworks/Steps_cfg.py',
              '--datacfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Productions_cfg.py',
            ],
        ('Autumn18_102X_nAODv6_Full2018v6','MC_signal') :[
              '--sitescfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Sites_cfg.py',
              '--modcfg SNuAnalytics/NanoGardenerFrameworks/Steps_cfg.py',
              '--datacfg SNuAnalytics/PostProcess/ChargedHiggsToCB/Productions_cfg.py',
            ],
      },

}


