#python signalKF.py SM matched_had_top_mass_flavCorr rand_had_top_mass_flavCorr 0 400
#python signalKF.py SM matched_mbl_flavCorr rand_mbl_flavCorr 0 300
#python signalKF.py SM matched_dijet_mass_flavCorr rand_dijet_mass_flavCorr 0 300
#python signalKF.py SM matched_dijet_deltaR rand_dijet_deltaR 0 7

python signalKF.py 075 matched_had_top_mass_flavCorr rand_had_top_mass_flavCorr 0 400
python signalKF.py 080 matched_had_top_mass_flavCorr rand_had_top_mass_flavCorr 0 400
python signalKF.py 085 matched_had_top_mass_flavCorr rand_had_top_mass_flavCorr 0 400
python signalKF.py 090 matched_had_top_mass_flavCorr rand_had_top_mass_flavCorr 0 400
python signalKF.py 100 matched_had_top_mass_flavCorr rand_had_top_mass_flavCorr 0 400
python signalKF.py 110 matched_had_top_mass_flavCorr rand_had_top_mass_flavCorr 0 400
python signalKF.py 120 matched_had_top_mass_flavCorr rand_had_top_mass_flavCorr 0 400
python signalKF.py 130 matched_had_top_mass_flavCorr rand_had_top_mass_flavCorr 0 400
python signalKF.py 140 matched_had_top_mass_flavCorr rand_had_top_mass_flavCorr 0 400
python signalKF.py 150 matched_had_top_mass_flavCorr rand_had_top_mass_flavCorr 0 400
python signalKF.py 160 matched_had_top_mass_flavCorr rand_had_top_mass_flavCorr 0 400

python signalKF.py 075 matched_mbl_flavCorr rand_mbl_flavCorr 0 300
python signalKF.py 080 matched_mbl_flavCorr rand_mbl_flavCorr 0 300
python signalKF.py 085 matched_mbl_flavCorr rand_mbl_flavCorr 0 300
python signalKF.py 090 matched_mbl_flavCorr rand_mbl_flavCorr 0 300
python signalKF.py 100 matched_mbl_flavCorr rand_mbl_flavCorr 0 300
python signalKF.py 110 matched_mbl_flavCorr rand_mbl_flavCorr 0 300
python signalKF.py 120 matched_mbl_flavCorr rand_mbl_flavCorr 0 300
python signalKF.py 130 matched_mbl_flavCorr rand_mbl_flavCorr 0 300
python signalKF.py 140 matched_mbl_flavCorr rand_mbl_flavCorr 0 300
python signalKF.py 150 matched_mbl_flavCorr rand_mbl_flavCorr 0 300
python signalKF.py 160 matched_mbl_flavCorr rand_mbl_flavCorr 0 300

python signalKF.py 075 matched_dijet_mass_flavCorr rand_dijet_mass_flavCorr 0 300
python signalKF.py 080 matched_dijet_mass_flavCorr rand_dijet_mass_flavCorr 0 300
python signalKF.py 085 matched_dijet_mass_flavCorr rand_dijet_mass_flavCorr 0 300
python signalKF.py 090 matched_dijet_mass_flavCorr rand_dijet_mass_flavCorr 0 300
python signalKF.py 100 matched_dijet_mass_flavCorr rand_dijet_mass_flavCorr 0 300
python signalKF.py 110 matched_dijet_mass_flavCorr rand_dijet_mass_flavCorr 0 300
python signalKF.py 120 matched_dijet_mass_flavCorr rand_dijet_mass_flavCorr 0 300
python signalKF.py 130 matched_dijet_mass_flavCorr rand_dijet_mass_flavCorr 0 300
python signalKF.py 140 matched_dijet_mass_flavCorr rand_dijet_mass_flavCorr 0 300
python signalKF.py 150 matched_dijet_mass_flavCorr rand_dijet_mass_flavCorr 0 300
python signalKF.py 160 matched_dijet_mass_flavCorr rand_dijet_mass_flavCorr 0 300

python signalKF.py 075 matched_dijet_deltaR rand_dijet_deltaR 0 7
python signalKF.py 080 matched_dijet_deltaR rand_dijet_deltaR 0 7
python signalKF.py 085 matched_dijet_deltaR rand_dijet_deltaR 0 7
python signalKF.py 090 matched_dijet_deltaR rand_dijet_deltaR 0 7
python signalKF.py 100 matched_dijet_deltaR rand_dijet_deltaR 0 7
python signalKF.py 110 matched_dijet_deltaR rand_dijet_deltaR 0 7
python signalKF.py 120 matched_dijet_deltaR rand_dijet_deltaR 0 7
python signalKF.py 130 matched_dijet_deltaR rand_dijet_deltaR 0 7
python signalKF.py 140 matched_dijet_deltaR rand_dijet_deltaR 0 7
python signalKF.py 150 matched_dijet_deltaR rand_dijet_deltaR 0 7
python signalKF.py 160 matched_dijet_deltaR rand_dijet_deltaR 0 7
